# Generated by Django 4.1.6 on 2023-02-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, null=True, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('semestreInicio', models.PositiveIntegerField(verbose_name='Inicio do Semestre')),
                ('semestreFim', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fim do Semestre')),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Trancado', 'Trancado'), ('Formado', 'Formado')], default='Ativo', max_length=8, verbose_name='Situação')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curso')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
    ]
